### ISSUE TITLE
Is it possible to find shadowed ACL rules?

### ISSUE THREAD

**Issue by molchanov1983** [makinacorpus/php-acl#1]
Hello
Is it possible to find shadowed ACL rule in file using your library?
File example: 
 2600 permit tcp host 78.21.116.74 54.67.112.258 0.0.0.1 eq smtp
 2610 permit tcp 61.132.228.0 0.0.21.155 54.58.222.108 0.0.0.1 eq smtp
 2620 permit tcp 48.132.128.0 0.0.21.155 54.58.112.108 0.0.0.1 eq ssh
 2630 permit tcp host 71.101.216.11 host 44.38.182.143 eq ssh

Thanks

**Comment by pounard** [comment]
I think you posted this into the wrong project.
